"""initial schema

Revision ID: 2384a284b398
Revises: 
Create Date: 2026-06-18 23:42:39.004213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.core.crypto  # noqa: F401 – required for EncryptedString column type


# revision identifiers, used by Alembic.
revision: str = '2384a284b398'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('query', sa.String(length=600), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=600), nullable=False),
    sa.Column('params', sa.String(length=200), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('took', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searches_cache_key'), 'searches', ['cache_key'], unique=False)
    op.create_table('selectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('field_type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password', src.core.crypto.EncryptedString(), nullable=True),
    sa.Column('hashed_password', src.core.crypto.EncryptedString(), nullable=True),
    sa.Column('name', src.core.crypto.EncryptedString(), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('phone', src.core.crypto.EncryptedString(), nullable=True),
    sa.Column('address', src.core.crypto.EncryptedString(), nullable=True),
    sa.Column('database_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_records_database_name'), 'result_records', ['database_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_records_database_name'), table_name='result_records')
    op.drop_table('result_records')
    op.drop_table('selectors')
    op.drop_index(op.f('ix_searches_cache_key'), table_name='searches')
    op.drop_table('searches')
    op.drop_table('targets')
    op.drop_table('investigations')
    op.drop_table('audit_log')
    op.drop_table('users')
    # ### end Alembic commands ###
